import type { UserProfile } from "../types/user-profile"

export const mockUserProfile: UserProfile = {
  id: "1",
  name: "Godoy Muñoz",
  username: "godoy_foodie_crazy",
  email: "godoyliam.dev@example.com",
  avatar: "/placeholder.svg?height=120&width=120",
  bio: "Passionate food explorer 🍽️ | NYC-based foodie | Always hunting for the next great meal | Wine enthusiast 🍷",
  location: "Lima, Perú",
  joinedDate: "2025-07-13",
  stats: {
    restaurantsVisited: 247,
    reviewsWritten: 89,
    followers: 1234,
    following: 567,
    photosShared: 342,
  },
  preferences: {
    favoriteCuisines: ["Italian", "Japanese", "Mediterranean", "French", "Thai"],
    dietaryRestrictions: ["Vegetarian Options"],
    priceRange: ["$$", "$$$"],
    diningStyle: ["Fine Dining", "Casual", "Brunch", "Date Night"],
  },
  achievements: [
    {
      id: "1",
      title: "Century Club",
      description: "Visited 100+ restaurants",
      icon: "🏆",
      unlockedDate: "2024-01-15",
      rarity: "epic",
    },
    {
      id: "2",
      title: "Review Master",
      description: "Written 50+ detailed reviews",
      icon: "✍️",
      unlockedDate: "2023-11-20",
      rarity: "rare",
    },
    {
      id: "3",
      title: "Cuisine Explorer",
      description: "Tried 15+ different cuisines",
      icon: "🌍",
      unlockedDate: "2023-08-10",
      rarity: "rare",
    },
    {
      id: "4",
      title: "Photo Enthusiast",
      description: "Shared 200+ food photos",
      icon: "📸",
      unlockedDate: "2024-02-01",
      rarity: "common",
    },
  ],
  recentVisits: [
    {
      id: "1",
      restaurantName: "Le Bernardin",
      cuisine: "French Seafood",
      rating: 5,
      visitDate: "2024-01-10",
      review: "Absolutely incredible tasting menu. The lobster course was perfection!",
      photos: ["/placeholder.svg?height=100&width=100"],
    },
    {
      id: "2",
      restaurantName: "Raku",
      cuisine: "Japanese",
      rating: 4.5,
      visitDate: "2024-01-05",
      review: "Amazing ramen and authentic atmosphere. Will definitely return.",
      photos: ["/placeholder.svg?height=100&width=100", "/placeholder.svg?height=100&width=100"],
    },
    {
      id: "3",
      restaurantName: "Don Angie",
      cuisine: "Italian-American",
      rating: 4,
      visitDate: "2023-12-28",
      review: "Creative take on Italian classics. The chrysanthemum salad was unique!",
      photos: ["/placeholder.svg?height=100&width=100"],
    },
  ],
  wishlist: [
    {
      id: "1",
      restaurantName: "Eleven Madison Park",
      cuisine: "Contemporary American",
      location: "Flatiron District",
      image: "/placeholder.svg?height=80&width=80",
      addedDate: "2024-01-01",
    },
    {
      id: "2",
      restaurantName: "Atomix",
      cuisine: "Korean",
      location: "NoMad",
      image: "/placeholder.svg?height=80&width=80",
      addedDate: "2023-12-15",
    },
  ],
  foodPhotos: [
    {
      id: "1",
      image: "/placeholder.svg?height=150&width=150",
      restaurantName: "Le Bernardin",
      dishName: "Lobster Thermidor",
      uploadDate: "2024-01-10",
      likes: 45,
    },
    {
      id: "2",
      image: "/placeholder.svg?height=150&width=150",
      restaurantName: "Raku",
      dishName: "Tonkotsu Ramen",
      uploadDate: "2024-01-05",
      likes: 32,
    },
    {
      id: "3",
      image: "/placeholder.svg?height=150&width=150",
      restaurantName: "Don Angie",
      dishName: "Chrysanthemum Salad",
      uploadDate: "2023-12-28",
      likes: 28,
    },
    {
      id: "4",
      image: "/placeholder.svg?height=150&width=150",
      restaurantName: "Via Carota",
      dishName: "Cacio e Pepe",
      uploadDate: "2023-12-20",
      likes: 51,
    },
  ],
}
